AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
